version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    docker:
      - image: circleci/node
      - image: circlci/mongo
          name: database
    working_directory: ~/reviews-service
    steps:
      - checkout
      run: npm install
      run: npm run build
      run: npm run seed
  # test:
  #   executor:
  #     name: node/default
  #   steps:
  #     - checkout
  #     - node/with-cache:
  #         steps:
  #           - run: npm install
  #           - run: npm test
  # lint:
  #   executor:
  #     name: node/default
  #   steps:
  #     - checkout
  #     - run: npm install
  #     - run: npm run eslint
  # deploy:
  #   steps:
  #     - checkout
  #     - run:
  #         command: |
  #           git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
    # lint, test, and deploy:
    #   jobs:
    #     - test
    #     - lint
        # - deploy:
        #   requires:
        #     - test
  build:
    jobs:
      - build