version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test



# version: 2.1
# jobs:
#   build:
#     working_directory: ~/reviews-service
#     steps:
#       - checkout
#       - run:
#         name: Build Docker Images
#         command: docker-compose up



# version: 2.1
# jobs:
#   build:
#     docker:
#       - image: circleci/node:12.16.1
#       - image: circleci/mongo:4.2-bionic-ram
#         name: database
#     working_directory: ~/reviews-service
#     steps:
#       - checkout
#       - run: npm install
#       - run: npm run build
#       - run: npm run boot-prod
#       # - run: npm run seed

# workflows:
#   version: 2
#   build:
#     jobs:
#       - build
