version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:12.16.1
      - image: circleci/mongo:4.2-bionic-ram
        name: database
    working_directory: ~/reviews-service
    steps:
      - checkout
      - run: npm install
      - run: npm test
workflows:
  version: 2
  test:
    jobs:
      - test
