version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:12.16.1
      - image: circleci/mongo:4.2-bionic-ram
        name: database
    working_directory: ~/reviews-service
    steps:
      - checkout
      - run: npm install
      - run: npm test
  deploy:
    machine: true
    working_directory: ~/reviews-service
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t axmitchell/reviews-service .
      - run:
          name: Push image to DockerHub
          command: |
            docker login -u "$DOCKERHUB_LOGIN" -p "$DOCKERHUB_PW"
            docker push axmitchell/reviews-service
      - run:
          name: Deploy to Heroku
          command: |
              docker login --username="$HEROKU_LOGIN" --password="$HEROKU_API_KEY" registry.heroku.com
              docker tag axmitchell/reviews-service registry.heroku.com/$HEROKU_APP_NAME/web
              docker push registry.heroku.com/$HEROKU_APP_NAME/web

workflows:
  version: 2.1
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
