version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    docker:
      - image: circleci/node
      - image: circlci/mongo
      name: database
    working_directory: ~/reviews-service
    steps:
      - checkout
      run: npm install
      run: npm run build
      run: npm run seed

workflows:
  build:
    jobs:
      - build