version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.16.1
      - image: circleci/mongo:4.2-bionic-ram
        name: database
    working_directory: ~/reviews-service
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm run seed

workflows:
  version: 2
  build:
    jobs:
      - build
